core/views.py
import os
from flask import Blueprint, render_template, jsonify
import requests,json 
from sqlalchemy import extract,asc
from models import *
import datetime
import urllib3
from pprint import pprint

core_bp = Blueprint('core_bp',__name__,template_folder='templates')

@core_bp.context_processor
def inject_now():
        return {'now': datetime.datetime.utcnow()}

@core_bp.route('/')
def index():
    days = Reservation.query.group_by(extract('year',Reservation.start), extract('month',Reservation.start), extract('day',Reservation.start)).order_by(Reservation.start.desc()).all()
    return render_template('core/index.html',days=days)


@core_bp.route('/today/',defaults={'mapa': 0})
@core_bp.route('/today/<int:mapa>',defaults={'mapa': 0})
def today(mapa):
    today = datetime.date.today()
    return day_display(today.year,today.month,today.day,mapa)

@core_bp.route('/<int:year>/<int:month>/<int:day>/',defaults={'mapa': 0})
@core_bp.route('/<int:year>/<int:month>/<int:day>/<int:mapa>')
def day_display(year,month,day,mapa):
    yesterday = datetime.date.today() - datetime.timedelta(days=1)
    previous_reservations = Reservation.query.join(Airspace).filter(extract('year',Reservation.start)==yesterday.year,extract('month',Reservation.start)==yesterday.month, extract('day',Reservation.start)==yesterday.day, extract('day',Reservation.end)==datetime.date(year=year,month=month,day=day).day).order_by(asc(Airspace.designator)).all()
    active = Reservation.query.join(Airspace).filter(extract('year',Reservation.start)==year,extract('month',Reservation.start)==month, extract('day',Reservation.start)==day,Reservation.status.has(Status.name=="ACTIVATED")).order_by(asc(Airspace.designator)).all()
    other= Reservation.query.join(Airspace).filter(extract('year',Reservation.start)==year,extract('month',Reservation.start)==month, extract('day',Reservation.start)==day, Reservation.status.has(Status.name!="ACTIVATED")).order_by(asc(Airspace.designator)).all()
    key = os.environ.get('GOOGLEMAPSAPIKEY')
    if (yesterday or active or other):
        return render_template('core/reservations.html',reservations=active, other=other, yesterday=previous_reservations,year=year,month=month,day=day,key=key,mapa=mapa)
    else:
        return index()

@core_bp.route('/airspace/<string:name>/')
@core_bp.route('/airspace/<string:name>/<int:page>')
def airspace_reservations(name,page=1):
        per_page=50
        reservations = Reservation.query.join(Airspace).filter(Airspace.designator==name).order_by(Reservation.start.desc()).paginate(page,per_page,error_out=False)
        airspace = Airspace.query.filter(Airspace.designator==name).first()
        key = os.environ.get('GOOGLEMAPSAPIKEY')
        gfx = "./static/images/strefa_"+name+".png"
        http = urllib3.PoolManager()
        points = ""
        if (len(airspace.coordinates)>1 and not os.path.exists(gfx)):
            max_lat = airspace.coordinates[0].lat
            max_lon = airspace.coordinates[0].lon
            min_lat = airspace.coordinates[0].lat
            min_lon = airspace.coordinates[0].lon
            for point in airspace.coordinates:
                if point.lat > max_lat:
                    max_lat = point.lat
                if point.lat < min_lat:
                    min_lat = point.lat
                if point.lon > max_lon:
                    max_lon = point.lon
                if point.lon < min_lon:
                    min_lon = point.lon
                points = points +"|"+str(point.lat)+','+str(point.lon)

            center_lat = (max_lat + min_lat) / 2
            center_lon = (max_lon + min_lon) / 2
            url='http://maps.googleapis.com/maps/api/staticmap?key='+key+'&center='+str(center_lat)+','+str(center_lon)+'&zoom=10&size=600x600&maptype=terrain&sensor=false&path=color:red|weight:2|fillcolor:white'+points+"|"+str(airspace.coordinates[0].lat)+","+str(airspace.coordinates[0].lon)

            response = http.request('GET', url)
            f = open(gfx, 'wb')
            f.write(response.data)
            f.close()

        return render_template('core/airspace.html',reservations=reservations,name=name,airspace=airspace,key=key)

@core_bp.route('/airspaces/')
def airspaces():
    airspaces = Airspace.query.group_by(Airspace.typ,Airspace.designator).all()
    spaces = {} 
    for airspace in airspaces:
        spaces.setdefault(airspace.typ, []).append(airspace.designator)
    return render_template('core/airspaces.html',spaces=spaces)

core/templates/core/airspace.html
{% extends 'core/base.html' %}
{% block title %}
Historia rezerwacji strefy {{ name }}
{% endblock %}
{% block map %}
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

{% if (airspace.coordinates is defined) and airspace.coordinates[0] %}
<script src="https://maps.googleapis.com/maps/api/js?key={{ key }}&callback=initMap&libraries=&v=weekly" async></script>

	<script>
	function initMap() {
		  const map = new google.maps.Map(document.getElementById("map"), {
			      zoom: 8,
			  center: { lat: {{ airspace.coordinates[0].lat }}, lng: {{ airspace.coordinates[0].lon }} },
			      mapTypeId: "terrain",
			    });
		  const airspaceCoords = [
				{% for c in airspace.coordinates %}
					{ lat: {{ c.lat }}, lng: {{ c.lon }} },
				{% endfor %}
			    ];
		  const airspace = new google.maps.Polygon({
			      paths: airspaceCoords,
			      strokeColor: "#808080",
			      strokeOpacity: 0.8,
			      strokeWeight: 2,
			      fillColor: "#808080",
			      fillOpacity: 0.35,
			    });
		  airspace.setMap(map);
	}

	</script>
<style>
#map{
	width: 100%;
	height: 300px;
}
</style>
{% endif %}

{% endblock %}

{% block ogmetadata %}

<meta property="og:title" content="Strefa {{ name }}" />
<meta property="og:description" content="Histora rezerwacji strefy  {{ name }} (na bazie UUP)" />
<meta property="og:image" content="http://uup.pgxc.pl{{ url_for('static', filename='images/strefa_'+name+'.png') }}" />
<meta property="og:url" content="http://uup.pgxc.pl{{ url_for('core_bp.airspace_reservations', name=name)}}" />
{% endblock %}

{% block content %}
<h1>Historyczne rezerwacje strefy powietrznej {{ name }}</h1>

<div id="map" class="container"></div>
{% if (reservations is defined) and reservations %}
<table class="table table-striped">
	<tr><th scope="col">Typ</th><th scope="col">Desygnator</th><th scope="col">Okres rezerwacji</th><th scope="col">Zakres wysokości</th><th scope="col">Uwagi</th><th scope="col">Status</th></tr>
{% for r in reservations.items %}
	<tr><td>{{ r.airspace.typ }}</td><td>{{ r.airspace.designator }}</td><td>{{ r.start }}Z - {{ r.end }}Z </td><td>{{r.lower_altitude }}-{{ r.upper_altitude }}{{ r.altitude_unit }}</td><td>{{ r.remarks }}</td><td>{{ r.status.name }}</td></tr>
{% endfor %}
</table>
	<nav aria-label="Nawigacja strony">
		<ul class="pagination justify-content-center">
			{% if reservations.has_prev %} <li class="page-item"><a class="page-link" href="{{ url_for('core_bp.airspace_reservations',page=reservations.prev_num,name=name) }}" ><span class="meta-nav">&larr;</span> Nowsze dane</a></li> {% else %}
				<li class="page-item disabled"><a class="page-link" href="#" ><span class="meta-nav">&larr;</span> Nowsze dane</a></li> {% endif %}
			<li class="page-item disabled"> <a class="page-link" href="#" ><span class="meta-nav">...</span></a> </li>
			{% if reservations.has_next %} <li class="page-item"> <a class="page-link" href="{{ url_for('core_bp.airspace_reservations',page=reservations.next_num,name=name) }}" >Starsze dane <span class="meta-nav">&rarr;</span></a> </li> {% else %}
			<li class="page-item disabled"> <a class="page-link" href="#" >Starsze dane <span class="meta-nav">&rarr;</span></a> </li> {% endif %}
		</ul>
	</nav>
<p><small>*Źródło UUP publikowany przez PANSA, lokalne dane aktualizowane co 30 minut <br>*Przed rozpoczęciem lotów zawsze potwierdź zajętość stref w FIS
<ul>
	<li>UAV/BSP - UNMANNED AERIAL VEHICLE/BEZZALOGOWY STATEK POWIETRZNY</li>
	<li>RPA - REMOTELY PILOTED AIRCRAFT/ZDALNIE STEROWANE BEZZALOGOWE STATKI POWIETRZNE</li>
	<li>/W - W PRZYPADKU KONFLIKTU ZE STRUKTURA Z PRZYZNANYM PRIORYTETEM ZEZWOLENIE JEST WYDAWANE WARUNKOWO /W - CONDITIONAL PERMISSION IN CASE OF A CONFLICT WITH AN AREA HAVING A PRIORITY</li>
	<li>CLN - STREFA KOLIZYJNA - PATRZ AIP ENR 2.2.2-2 PUNKT 4 / CONFLICT AREA - SEE AIP ENR 2.2.2-2 POINT 4</li>
</ul>
</small>
</p>
{% else %}
Brak danych
{% endif %}
{% endblock %}

core/templates/core/airspaces.html
{% extends 'core/base.html' %}
{% block title %}
Lista zarchiwizowanych stref powietrznych
{% endblock %}
{% block content %}
<h1>Lista zarchiwizowanych stref powietrznych</h1>
<p>Strona pozwala sprawdzić archiwalne informacje dotyczące stref, dane na których bazuje strona gromadzone są od dnia 25 marca 2021.</p>
{% if (spaces is defined) and spaces %}
{% for s in spaces %}
<h2>{{ s }}</h2>
<div class="row">
	{% for designator in spaces[s] %}
	<div class="col-md-1 m-2"><a href="{{ url_for('core_bp.airspace_reservations',name=designator) }}"><button type="button" class="btn btn-outline-info">{{ designator }}</button></a></div>
	{% endfor %}
</div>
{% endfor %}
{% else %}
Brak danych
{% endif %}
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    {% block ogmetadata %}
    {% endblock %}
    <title>Rezerwacje stref powietrznych {% block title %}{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static',filename='images/favicon.png') }}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>"

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7B49GS2JC6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7B49GS2JC6');
</script>
{% block map %}
{% endblock %}

  </head>

  <body class="d-flex flex-column h-100">

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	    <a class="navbar-brand" href="{{ url_for('core_bp.index') }}">UUP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
		  <a class="nav-link" href="{{ url_for('core_bp.today') }}">Dzisiejszy AUP/UUP<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
		  <a class="nav-link" href="{{ url_for('core_bp.airspaces') }}">Lista Stref<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://leonardo.pgxc.pl">Polski Serwer LeonardoXC</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="flex-shrink-0">
	<div class="container">
	{% block content %}
	{% endblock %}
	</div>
    </main>

    <footer class="footer mt-auto py-3 bg-light">
	      <div class="container">
		      <span class="text-muted">Dane gromadzone na potrzeby paralotniarzy korzystających z <a href="https://leonardo.pgxc.pl">Polskiego Serwera LeonardoXC</a><br>
			<small>Serwis wykorzystuje pliki cookies. Korzystając ze strony wyrażasz zgodę na wykorzystywanie plików cookies. <a class="ctcc-more-info-link" tabindex=0 target="_blank" href="http://pgxc.pl/cookie-policy/">dowiedz się więcej.</a></small>
		      </span>
		
		</div>
    </footer>
      <script src="https://getbootstrap.com/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
			
  </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}
	Informacje o projekcie
{% endblock %}
{% block content %}
<h1>Strona gromadząca archiwalne dane z UUP airspace.pansa.pl</h1>
<p>Strona zawiera archiwalne rekordy dotyczące rezerwacji przestrzeni powietrznej publikowane na airspace.pansa.pl. Ważne jest tu wyjaśnienie, iż podczas przygotowania do lotu należy zawsze weryfikować informacje dzwoniąc na infolinię FIS. Statusy w archiwach mają znaczenie pomocnicze i nie są gawarantem takiego stanu rzeczy. Status ACTIVATED oznacza, że strefa była aktywowana, status PLANNED oznacza że zaplanowano rezerwację (jednak sam fakt zmiany statusu na ACTIVATED nie wyklucza jej aktywacji w danym dniu).
</p>
<h2>Status projektu</h2>
<p>W chwili obecnej:
 <ul>
	 <li>przygotowałem podstawy szablonu, który za jakiś czas zostanie dostosowany do aplikacji,</li>
	 <li>gromadzone są dane z UUP, aktualizacje lokalnej bazy danych robione są w interwale 30 minutowym,</li>
 	 <li>można wyświetlać dane z wewnętrznej bazy danych,</li>
	 <li>przygotowane menu pozwalające wybrać archiwalną datę z podziałem na miesiące,</li>
 </ul>
 TODO:
 <ul>
	 <li>integracja z wewnętrznymi mechanizmami <a href="https://leonardo.pgxc.pl">leonardo.pgxc.pl</a>,</li>
	 <li>przygotować mechanizmy archiwizujące punkty graniczne stref publikowanych w UUP/AUP</li>
 </ul>
 <h2>Zarchiwizowane zapisy UUP</h2>
 <ul>
 {% for year,year_group in days |groupby('start.year')|reverse %}
 	{% for month, list in year_group|groupby('start.month')|reverse %}
	<div class="dropdown"> 
		<button class="btn btn-secondary dropdown-toggle" type="button" id="{{year}}_{{month}}Primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ year }} / {{ month }}</button>
		<div class="dropdown-menu" aria-labelledby="{{year}}_{{month}}Primary">
		{% for day in list %}
 			<a class="dropdown-item" href="{{ url_for('core_bp.day_display',year=day.start.year,month=day.start.month,day=day.start.day) }}">{{ day.start.year }}/{{ day.start.month }}/{{ day.start.day }}</a>
		{% endfor %}
		</div>
	</div>
	<br>
	{% endfor %}
 {% endfor %}
 </ul>
</p>
{% endblock %}

core/templates/core/reservations.html
{% extends 'core/base.html' %}
{% block title %}
{{ year }}-{{ month }}-{{ day }}
{% endblock %}

{% block map %}
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

<script src="https://maps.googleapis.com/maps/api/js?key={{ key }}&callback=initMap&libraries=&v=weekly" async></script>

	<script>
	function initMap() {
		  const map = new google.maps.Map(document.getElementById("map"), {
			      zoom: 5,
			  center: { lat: 52.0692, lng: 19.4773 },
			      mapTypeId: "terrain",
			    });
		  {% for r in yesterday %}
			const y{{ r.id }}Coords = [
				{% for c in r.airspace.coordinates %}
					{ lat: {{ c.lat }}, lng: {{ c.lon }} },
				{% endfor %}
			    ];
			const y{{ r.id }} = new google.maps.Polygon({
			    paths: y{{ r.id }}Coords,
				{% if r.status.name == "ACTIVATED" %}
			      		strokeColor: "#FF0000",
			      		fillColor: "#FF0000",
				{% else %}
			      		strokeColor: "#FFFF00",
			      		fillColor: "#FFFF00",
				{% endif %}
			      strokeOpacity: 0.8,
			      strokeWeight: 2,
			      fillOpacity: 0.35,
			    });
			y{{ r.id }}.setMap(map);
		  {% endfor %}
		  {% for r in reservations %}
			const r{{ r.id }}Coords = [
				{% for c in r.airspace.coordinates %}
					{ lat: {{ c.lat }}, lng: {{ c.lon }} },
				{% endfor %}
			    ];
			const r{{ r.id }} = new google.maps.Polygon({
			    paths: r{{ r.id }}Coords,
				{% if r.status.name == "ACTIVATED" %}
			      		strokeColor: "#FF0000",
			      		fillColor: "#FF0000",
				{% else %}
			      		strokeColor: "#FFFF00",
			      		fillColor: "#FFFF00",
				{% endif %}
			      strokeOpacity: 0.8,
			      strokeWeight: 2,
			      fillOpacity: 0.35,
			    });
			r{{ r.id }}.setMap(map);
		  {% endfor %}
		  {% for r in other %}
			const o{{ r.id }}Coords = [
				{% for c in r.airspace.coordinates %}
					{ lat: {{ c.lat }}, lng: {{ c.lon }} },
				{% endfor %}
			    ];
			const o{{ r.id }} = new google.maps.Polygon({
			    paths: o{{ r.id }}Coords,
				{% if r.status.name == "ACTIVATED" %}
			      		strokeColor: "#FF0000",
			      		fillColor: "#FF0000",
				{% else %}
			      		strokeColor: "#FFFF00",
			      		fillColor: "#FFFF00",
				{% endif %}
			      strokeOpacity: 0.8,
			      strokeWeight: 2,
			      fillOpacity: 0.35,
			    });
			o{{ r.id }}.setMap(map);
		  {% endfor %}
	}

	</script>
<style>
#map{
	width: 100%;
	height: 300px;
	{% if mapa == 1 %}
	display: block;
	{% else %}
	display: none;
	{% endif %}
}
</style>

{% endblock %}
{% block content %}
<h1>Stan stref powietrznych na dzień {{ year }}-{{ month }}-{{ day }}</h1>
<div id="map" class="container"></div>
{% if (yesterday is defined) and yesterday %}
<h2>Strefy rezerwowane w dniu poprzednim, których rezerwacja kończy się w dniu {{ year }}-{{ month }}-{{ day }}*</h2>
<table class="table table-striped">
	<tr><th scope="col">Typ</th><th scope="col">Desygnator</th><th scope="col">Okres rezerwacji</th><th scope="col">Zakres wysokości</th><th scope="col">Uwagi</th><th scope="col">Status</th></tr>
{% for r in yesterday %}
<tr><td>{{ r.airspace.typ }}</td><td><a href="{{ url_for('core_bp.airspace_reservations',name=r.airspace.designator) }}">{{ r.airspace.designator }}</a></td><td>{{ r.start }}Z - {{ r.end }}Z </td><td>{{r.lower_altitude }}-{{ r.upper_altitude }}{{ r.altitude_unit }}</td><td>{{ r.remarks }}</td><td>{{ r.status.name }}</td></tr>
{% endfor %}
</table>
{% endif %}

{% if (reservations is defined) and reservations %}
<h2>Strefy aktywowane {{ year }}-{{ month }}-{{ day }}*</h2>
<table class="table table-striped">
	<tr><th scope="col">Typ</th><th scope="col">Desygnator</th><th scope="col">Okres rezerwacji</th><th scope="col">Zakres wysokości</th><th scope="col">Uwagi</th><th scope="col">Status</th></tr>
{% for r in reservations %}
<tr><td>{{ r.airspace.typ }}</td><td><a href="{{ url_for('core_bp.airspace_reservations',name=r.airspace.designator) }}">{{ r.airspace.designator }}</a></td><td>{{ r.start }}Z - {{ r.end }}Z </td><td>{{r.lower_altitude }}-{{ r.upper_altitude }}{{ r.altitude_unit }}</td><td>{{ r.remarks }}</td><td>{{ r.status.name }}</td></tr>
{% endfor %}
</table>
{% endif %}

{% if (other is defined) and other %}
<h2>Strefy zarezerwowane, bez potwierdzenia aktywacji*</h2>
<table class="table table-striped" > 
	<tr><th scope="col">Typ</th><th cope="col">Desygnator</th><th scope="col">Okres rezerwacji</th><th scope="col">Zakres wysokości</th><th scope="col">Uwagi</th><th scope="col">Status</th></tr>
{% for r in other %}
<tr><td>{{ r.airspace.typ }}</td><td><a href="{{ url_for('core_bp.airspace_reservations',name=r.airspace.designator) }}">{{ r.airspace.designator }}</a></td><td>{{ r.start }}Z - {{ r.end }}Z </td><td>{{r.lower_altitude }}-{{ r.upper_altitude }}{{ r.altitude_unit }}</td><td>{{ r.remarks }}</td><td>{{ r.status.name }}</td></tr>
{% endfor %}
</table>
{% endif %}

<p><small>*Źródło AUP oraz UUP publikowany przez PANSA, lokalne dane aktualizowane co 30 minut <br>*Przed rozpoczęciem lotów zawsze potwierdź zajętość stref w FIS
<ul>
	<li>UAV/BSP - UNMANNED AERIAL VEHICLE/BEZZALOGOWY STATEK POWIETRZNY</li>
	<li>RPA - REMOTELY PILOTED AIRCRAFT/ZDALNIE STEROWANE BEZZALOGOWE STATKI POWIETRZNE</li>
	<li>/W - W PRZYPADKU KONFLIKTU ZE STRUKTURA Z PRZYZNANYM PRIORYTETEM ZEZWOLENIE JEST WYDAWANE WARUNKOWO /W - CONDITIONAL PERMISSION IN CASE OF A CONFLICT WITH AN AREA HAVING A PRIORITY</li>
	<li>CLN - STREFA KOLIZYJNA - PATRZ AIP ENR 2.2.2-2 PUNKT 4 / CONFLICT AREA - SEE AIP ENR 2.2.2-2 POINT 4</li>
</ul>
</small>
</p>
{% endblock %}

core/templates/core/uup.html
<table>
	<tr><th>Rodzaj strefy</th><th>Desygnator</th><th colspan=6>Rezerwacje</th></tr>
	<tr><th></th><th></th><th>Godziny rezerwacji</th><th>Wysokość rezerwacji</th><th>Jednostka rezerwująca</th><th>Notatki</th><th>Status</th></tr>
{% for x in uup %}
<tr><td>{{ x['properties']['airspaceElementType'] }}</td><td colspan=6>{{ x['properties']['designator'] }}</td>
		{% for reservation in x['properties']['airspaceReservations'] %}
		<tr><td colspan=2></td><td>{{ reservation['startDate'][12:21] }} - {{ reservation['endDate'][12:21] }}</td><td>{{ reservation['lowerAltitude'] }} - {{ reservation['upperAltitude'] }}{{ reservation['altitudeUnit'] }}</td><td> {{ reservation['unit'] }}</td><td>{{ reservation['remarks'] }}</td><td>{{ reservation['reservationStatus'] }}</td></tr>
		{% endfor %}
</tr>
{% endfor %}
</table>